# Copyright (c) 2025 CoReason, Inc.
#
# This software is proprietary and dual-licensed.
# Licensed under the Prosperity Public License 3.0 (the "License").
# A copy of the license is available at https://prosperitylicense.com/versions/3.0.0
# For details, see the LICENSE file.
# Commercial use beyond a 30-day trial requires a separate license.
#
# Source Code: https://github.com/CoReason-AI/coreason_sandbox

"""Data models for execution results."""

from typing import List
from pydantic import BaseModel, Field


class FileReference(BaseModel):
    """Represents a reference to a file artifact."""

    name: str = Field(..., description="The name of the file.")
    path: str = Field(..., description="The remote path of the file in the sandbox.")
    content: bytes = Field(None, description="The content of the file, if retrieved.")


class ExecutionResult(BaseModel):
    """Represents the result of a code execution in the sandbox."""

    stdout: str = Field(..., description="The standard output of the execution.")
    stderr: str = Field(..., description="The standard error of the execution.")
    exit_code: int = Field(..., description="The exit code of the execution.")
    artifacts: List[FileReference] = Field(
        default_factory=list, description="A list of file artifacts generated by the execution."
    )
    execution_duration: float = Field(..., description="The duration of the execution in seconds.")
